name: vector_map_tiles_example
description: A simple example demonstrating vector_map_tiles usage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0-0 <4.0.0"
  flutter: '>=3.37.0-0'

dependencies:
  flutter:
    sdk: flutter
  vector_map_tiles:
    path: ../
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  vector_tile_renderer: ^7.0.0-beta.1
    #path: ../../vector_tile_renderer

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
