name: vector_map_tiles
description: "A new Flutter package project."
version: 10.0.0-beta.1
homepage:

environment:
  sdk: ">=3.6.0-0 <4.0.0"
  flutter: '>=3.37.0-0'

dependencies:
  executor_lib: ^1.1.2
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  http: ^1.5.0
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  stash: ^5.2.0
  stash_file: ^5.2.0
  stash_memory: ^5.2.0
  vector_tile_renderer: ^7.0.0-beta.1
    #path: ../vector_tile_renderer

dev_dependencies:
  test: ^1.24.0
  flutter_lints: ^4.0.0
